# Pandas
- Pandas is a popular library in Python used for data analysis and manipulation. It helps you work with structured data like tables (similar to Excel spreadsheets or SQL tables).

### What Pandas is used for
- Cleaning and preparing data
- Reading/writing data (CSV, Excel, databases, etc.)
- Filtering, sorting, and grouping data
- Performing calculations and statistics
- Handling missing values
- It’s powerful, easy to use, and integrates well with other tools like:  NumPy (for numerical operations), Matplotlib / Seaborn (for visualization), Machine learning libraries
### Core data structures
- Series → a single column (1D data)
- DataFrame → a table (rows and columns)
- different operations

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Col1', 'Col2', 'Col3', 'Col4'])
print(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [5]:
df.to_csv('myDataFrame.csv')

In [6]:
# accessing the element of the dataframe
# .loc Labels / Names "a", "Age" (index and columns)
# .iloc Integer Positions,0, 1, 2
print(df['Col1'])
print(df.loc["Row1"])

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int64
Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [9]:
df.loc['Row1'] # to get the first row of the dataframe

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [14]:
df.loc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [15]:
df.loc["Row1":"Row2", "Col1":"Col2"] # to get the first two rows of the dataframe

      Col1  Col2
Row1     0     1
Row2     4     5

In [16]:
df.iloc[0:2, 0:2] # to get the first two rows and first two columns of the dataframe using iloc

      Col1  Col2
Row1     0     1
Row2     4     5

In [52]:
df.iloc[0:3:, 0:2] # to check the type of the dataframe

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9

In [53]:
type(df.loc["Row1"]) # to check the type of the dataframe using loc

pandas.Series

In [57]:
df.iloc[0:3, 0:2] # to get the first two rows and first two columns of the dataframe using iloc

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9

In [18]:
type(df.iloc[0:3, 0:]) # to check the type of the dataframe

pandas.DataFrame

In [19]:
df.iloc[0:, 1:]

      Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [21]:
# dataframe converted to numpy array
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [62]:
df.iloc[0:3, 0:2].values # to get the first two rows and first two columns of the dataframe using iloc

array([[0, 1],
       [4, 5],
       [8, 9]])

In [24]:
df.iloc[0:3,0:2].values.shape # to check the shape of the dataframe

(3, 2)

In [25]:
df.isnull()

       Col1   Col2   Col3   Col4
Row1  False  False  False  False
Row2  False  False  False  False
Row3  False  False  False  False
Row4  False  False  False  False
Row5  False  False  False  False

In [27]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [28]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [31]:
df["Col3"]

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Col3, dtype: int64

In [32]:
df[["Col1", "Col2"]]

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [33]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [3]:
df2=pd.read_csv('myDataFrame.csv', sep=',')
df2.head()

  Unnamed: 0  Col1  Col2  Col3  Col4
0       Row1     0     1     2     3
1       Row2     4     5     6     7
2       Row3     8     9    10    11
3       Row4    12    13    14    15
4       Row5    16    17    18    19

In [4]:
df2=pd.read_csv('benz.csv')

In [5]:
df2.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [7]:
df2.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df2['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [12]:
df2[df2['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [13]:
from io import StringIO, BytesIO

In [55]:
data=('col1,col2,col3\n'
       'a,b,1\n'
       'c,d,2\n'
       'e,f,3')

In [56]:
type(data)

str

In [58]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    c    d     2
2    e    f     3

In [ ]:
# get secific cols 

df=pd.read_csv(StringIO(data), usecols=['col1','col2'])
print(df)

  col1 col2
0    a    b
1    c    d
2    e    f

In [60]:
df.to_csv('test.csv')

In [79]:
# secifying cloms data types

data =('a,b,c,d\n'
    '1,2,3,4\n'
    '5,6,7,8\n'
    '9,10,11,12')

In [78]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [74]:
df=pd.read_csv(StringIO(data),dtype='object')
print(df)

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [75]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [85]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})
df

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [87]:
df['a'][1]

np.int64(5)

In [89]:
df.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [100]:
data1= ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [107]:
pd.read_csv(StringIO(data1),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [118]:
data1= ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')

In [119]:
pd.read_csv(StringIO(data1))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [120]:
pd.read_csv(StringIO(data1),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow